# Generated by Django 4.1 on 2024-08-20 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fee', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Student.course')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.course')),
                ('sec', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Student.section')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uroll', models.IntegerField(default=0)),
                ('uname', models.CharField(default=0, max_length=100)),
                ('uemail', models.EmailField(default=0, max_length=254, primary_key=True, serialize=False)),
                ('upass', models.CharField(default=0, max_length=30)),
                ('umob', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('section', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Student.section')),
                ('ucourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.course')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mob', models.DecimalField(decimal_places=0, default=None, max_digits=10)),
                ('doj', models.DateField(default=None)),
                ('dob', models.DateField(default=None)),
                ('pswd', models.CharField(default=None, max_length=100)),
                ('subjects', models.ManyToManyField(to='Student.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Student.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Student.subject')),
            ],
        ),
    ]
