# Generated by Django 4.1 on 2024-08-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='sec',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
