# Generated by Django 4.1 on 2024-08-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_remove_student_section_remove_subject_sec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
